package converter

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// TestIssueRegressions pins the examples from reported issues, copied
// verbatim from the issue text, to the full expected output. Unlike the
// goldens, these expectations are written by hand: `go test -update` never
// touches them, so a regression can't be accepted by regenerating files.
//
// Each output must also be free of TODO flags, carry legacy-syntax notes on
// exactly the listed source lines and, when a Lua compiler is on PATH, pass
// `luac -p`.
func TestIssueRegressions(t *testing.T) {
	cases := []struct {
		name   string
		in     string
		want   string
		legacy []int // source lines that must carry a NoteLegacy
	}{
		{
			// #9, "Input" block: since Hyprland 0.48 'windowrule' takes the
			// v2 grammar, so KEY:VALUE fields are matchers, not a v1 regex.
			name: "issue 9 input",
			in: `windowrule = float, class:^(big)$
windowrule = size 800 600, class:^(big)$, title:^(x)$
windowrulev2 = float, class:^(big)$
`,
			want: `-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(big)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(big)$",
        title = "^(x)$",
    },
    size = "800 600",
})

hl.window_rule({
    match = {
        class = "^(big)$",
    },
    float = true,
})
`,
		},
		{
			// #9, the wiki's XWayland drag rule quoted in "Impact". Numeric
			// match values are fine: hl.window_rule stringifies them.
			name: "issue 9 wiki xwayland rule",
			in: `windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
`,
			want: `-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})
`,
		},
		{
			// #9, "Suggestion": a bare regex has no matcher and stays v1.
			// Hyprland 0.48+ rejected the line, so the report says so.
			name:   "issue 9 bare regex stays v1",
			legacy: []int{1},
			in: `windowrule = float, ^(kitty)$
`,
			want: `-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(kitty)$",
    },
    float = true,
})
`,
		},
		{
			// #10, "Input" block: hyprlang variable names run to the '=',
			// so '-' is part of the name and references resolve whole.
			name: "issue 10 input",
			in: `$looking-glass = looking-glass-client
bind = SUPER, W, exec, $looking-glass
$gnome-schema = org.gnome.desktop.interface
$theme-cmd = gsettings set $gnome-schema gtk-theme Adwaita
exec-once = $theme-cmd
`,
			want: `-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local looking_glass = "looking-glass-client"
hl.bind("SUPER + W", hl.dsp.exec_cmd(looking_glass))
local gnome_schema = "org.gnome.desktop.interface"
local theme_cmd = "gsettings set " .. gnome_schema .. " gtk-theme Adwaita"

hl.on("hyprland.start", function()
    hl.exec_cmd(theme_cmd)
end)
`,
		},
	}
	luac := lookLuaSyntaxChecker()
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, rep, err := Convert(tc.in)
			if err != nil {
				t.Fatalf("Convert: %v", err)
			}
			// Trailing blank lines are layout, not what these cases pin.
			if strings.TrimRight(got, "\n") != strings.TrimRight(tc.want, "\n") {
				t.Errorf("output mismatch\n--- got ---\n%s\n--- want ---\n%s", got, tc.want)
			}
			if rep.Flagged != 0 || strings.Contains(got, "TODO: manual review") {
				t.Errorf("expected no TODO flags, got %d: %v", rep.Flagged, rep.Notes)
			}
			var legacy []int
			for _, n := range rep.Notes {
				if n.Kind == NoteLegacy {
					legacy = append(legacy, n.Line)
				}
			}
			if !slices.Equal(legacy, tc.legacy) || rep.Legacy != len(tc.legacy) {
				t.Errorf("legacy notes on lines %v (Legacy=%d), want %v: %+v", legacy, rep.Legacy, tc.legacy, rep.Notes)
			}
			if luac != "" {
				path := filepath.Join(t.TempDir(), "out.lua")
				if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
					t.Fatal(err)
				}
				checkLuaSyntax(t, luac, path)
			}
		})
	}
}
