-- Window rules, workspace rules, layer rules.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(Code)$",
    },
    opacity = 0.95,
})

hl.window_rule({
    match = {
        class = "mpv",
    },
    float = true,
})

hl.workspace_rule({
    workspace = "1",
    persistent = true,
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "special:magic",
    gaps_out = 30,
})

hl.layer_rule({
    match = { namespace = "waybar" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "gtk-layer-shell" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "rofi" },
    ignore_alpha = 0.5,
})

