-- Edge cases: escaped commas in exec, line continuation, devices, source.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
    accel_profile = "flat",
})

-- Escaped comma inside an exec arg.
hl.bind("SUPER + R", hl.dsp.exec_cmd("sh -c 'echo a,b'"))

-- Line continuation in a value.
hl.bind("SUPER + T", hl.dsp.exec_cmd("sh -c     'echo continued'"))

-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")
-- Source: ./mocha.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("mocha")

-- Top-level flattened syntax.

hl.config({
    general = {
        gaps_in = 7,
    },
})

-- Gesture.
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Permissions.
hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
