-- Edge cases: escaped commas in exec, line continuation, devices, source.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
    accel_profile = "flat",
})

-- Escaped comma inside an exec arg.
hl.bind("SUPER + R", hl.dsp.exec_cmd("sh -c 'echo a,b'"))

-- Unescaped commas in an exec arg: Hyprland's CVarList(value, 4) stops
-- splitting at the dispatcher, so the command keeps its commas AND its
-- original spacing.
hl.bind("SUPER + X", hl.dsp.exec_cmd("sh -c \"echo a,b,c\""))
hl.bind("SUPER + Y", hl.dsp.exec_cmd("notify-send \"one,two\" \"three, four\""), { description = "Notify" })

-- Line continuation in a value.
hl.bind("SUPER + T", hl.dsp.exec_cmd("sh -c     'echo continued'"))

-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")
-- Source: ./mocha.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("mocha")

-- Top-level flattened syntax.

hl.config({
    general = {
        gaps_in = 7,
    },
})

-- Gesture.
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Permissions.
hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })

-- env values are split on the FIRST comma only — the rest is the value.
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("LIST_VAR", "a,b,c")
hl.env("PATH_LIKE", "/opt/one,/opt/two", true)

-- …but a value with no comma at all has no name/value pair to emit.
-- TODO: manual review — malformed env on line 39: NO_COMMA

-- hyprlang variable names run to the '=': '-' is legal, and a reference
-- resolves to the longest declared name (hyprlang's own lookup order).
local looking_glass = "looking-glass-client"
local gnome_schema = "org.gnome.desktop.interface"
local theme_cmd = "gsettings set " .. gnome_schema .. " gtk-theme Adwaita"
local main_mod = "SUPER"
hl.bind(main_mod .. " + W", hl.dsp.exec_cmd(looking_glass .. " --home $HOME"))
-- Names that spell the same Lua local, or a Lua keyword, stay distinct.
local dup_name = "one"
local dup_name_2 = "two"
local end_ = "three"

hl.on("hyprland.start", function()
    hl.exec_cmd(theme_cmd)
    hl.exec_cmd("echo " .. dup_name .. " " .. dup_name_2 .. " " .. end_)
end)

