-- Fixture covering the typed-Lua-API migrations and the single polyfill
-- that survives (source glob) — kept as one file so the golden catches
-- drift across all the corrected shapes.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- hyprlang2lua polyfills — runtime helpers reproducing
-- hyprlang behaviour the typed Lua API doesn't expose directly.

local function hl_source_glob(pattern)
    -- 'source = path/*.conf' had hyprlang glob and inline-expand the
    -- matches. require() can't glob, so we shell out to ls (matching
    -- the user's brace-expansion behaviour) and dofile each result.
    -- Paths with spaces or shell metacharacters in the directory
    -- portion will misparse; typical ~/.config/hypr/ layouts don't
    -- hit this. Swap to lfs.dir() or find -name if you need fancier.
    local p = io.popen("ls " .. pattern .. " 2>/dev/null")
    if not p then return end
    for f in p:lines() do
        local chunk, err = loadfile(f)
        if chunk then chunk()
        else io.stderr:write("hl_source_glob: " .. tostring(err) .. "\n") end
    end
    p:close()
end

local mainMod = "SUPER"

hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland", true)

-- Source: ~/.config/hypr/conf.d/*.conf (glob; resolved at runtime). Each matched .conf must be converted to .lua.
hl_source_glob("~/.config/hypr/conf.d/*.lua")

hl.bind(mainMod .. " + J", hl.dsp.window.signal({ signal = 9 }))
hl.bind(mainMod .. " + Q", hl.dsp.window.kill("class:^firefox$"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))

hl.bind(mainMod .. " + R", function() hl.exec_cmd("hyprctl reload") end)

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1, on_current_monitor = true }))
hl.bind(mainMod .. " + SHIFT + 1", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "DP-2" })) end)

hl.bind(mainMod .. " + K", hl.dsp.window.float({ action = "toggle" }))

hl.bind(mainMod .. " + S", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
    hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("echo $HOME"))
hl.config({
    general = {
        gaps_in = { top = 5, right = 10, bottom = 15, left = 20 },
        gaps_out = { top = 5, right = 10, bottom = 5, left = 10 },
        border_size = 2,
    },
    -- env: no propagation (no third arg to hl.env).
    -- envd: dbus=true propagates to systemd/D-Bus per Hyprland source.
    -- Undeclared $XDG_* survives literally so /bin/sh expands it at exec time.
    -- execr-once uses the native hl.dsp.exec_raw dispatcher (no helper).
    -- Source glob is the one case that still needs a helper.
    -- Dispatchers that the API moved to typed tables.
    -- loadconfig has no dispatcher in 0.55+; inline a function literal.
    -- focusworkspaceoncurrentmonitor is native (on_current_monitor field).
    -- movecurrentworkspacetomonitor needs a runtime active-workspace lookup.
    -- hyprctl-dispatch exec rewrite.
    -- submap transformation.
    -- Undeclared $HOME survives in the shell payload.
})

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start $XDG_CURRENT_DESKTOP")
    hl.dispatch(hl.dsp.exec_raw("swayidle -w timeout 300 'swaylock -f'"))
end)

