-- Fixture covering the typed-Lua-API migrations and the single polyfill
-- that survives (source glob) — kept as one file so the golden catches
-- drift across all the corrected shapes.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

hl.config({
    general = {
        gaps_in = { top = 5, right = 10, bottom = 15, left = 20 },
        gaps_out = { top = 5, right = 10, bottom = 5, left = 10 },
        border_size = 2,
    },
})

-- env: no propagation (no third arg to hl.env).
hl.env("XCURSOR_SIZE", "24")
-- envd: dbus=true propagates to systemd/D-Bus per Hyprland source.
hl.env("XDG_CURRENT_DESKTOP", "Hyprland", true)

-- Undeclared $XDG_* survives literally so /bin/sh expands it at exec time.

-- execr-once uses the native hl.dsp.exec_raw dispatcher (no helper).

-- Source glob is the one case that still needs a helper.
-- TODO: manual review — glob source "~/.config/hypr/conf.d/*.conf" has no static Lua require() form. Enable --polyfill to emit hl_source_glob, or expand the glob manually.

-- Dispatchers that the API moved to typed tables.
hl.bind(mainMod .. " + J", hl.dsp.window.signal({ signal = 9 }))
hl.bind(mainMod .. " + Q", hl.dsp.window.kill("class:^firefox$"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))

-- loadconfig has no dispatcher in 0.55+; inline a function literal.
hl.bind(mainMod .. " + R", function() hl.exec_cmd("hyprctl reload") end)

-- focusworkspaceoncurrentmonitor is native (on_current_monitor field).
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1, on_current_monitor = true }))
-- movecurrentworkspacetomonitor needs a runtime active-workspace lookup.
hl.bind(mainMod .. " + SHIFT + 1", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "DP-2" })) end)

-- hyprctl-dispatch exec rewrite.
hl.bind(mainMod .. " + K", hl.dsp.window.float({ action = "toggle" }))

-- submap transformation.
hl.bind(mainMod .. " + S", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
    hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
    hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Undeclared $HOME survives in the shell payload.
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("echo $HOME"))

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start $XDG_CURRENT_DESKTOP")
    hl.dispatch(hl.dsp.exec_raw("swayidle -w timeout 300 'swaylock -f'"))
end)

