-- Conversion surface added in Hyprland 0.56. Binds come first because merge
-- mode flushes hl.config last, which would otherwise absorb these comments.

-- 'x' bind flag → allow_input_capture, alone and combined.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("SUPER + X", hl.dsp.exec_cmd("foo"), { allow_input_capture = true })
hl.bind("SUPER + Y", hl.dsp.exec_cmd("bar"), { locked = true, allow_input_capture = true })

-- Dispatcher added in 0.56 on both front-ends at once.
hl.bind("SUPER + Z", hl.dsp.release_input_capture())

-- Mouse-bind aspect-ratio modes. Only expressible in Lua since 0.56, and only
-- meaningful on a mouse bind: hyprlang hands bindm the whole third field, so
-- the ratio arrives as part of the dispatcher name. Anything that isn't 1 or 2
-- falls back to an unconstrained resize, matching Actions::mouse.
hl.bind("ALT + mouse:273", hl.dsp.window.resize({ keep_aspect_ratio = true }))
hl.bind("ALT + mouse:274", hl.dsp.window.resize({ keep_aspect_ratio = false }))
hl.bind("ALT + mouse:275", hl.dsp.window.resize())
hl.bind("ALT + mouse:276", hl.dsp.window.resize())
hl.bind("ALT + mouse:272", hl.dsp.window.drag())

-- Hyphenated section — the Lua registry spells it 'input_capture'.

hl.config({
    input_capture = {
        capture_modifiers = true,
        enforce_barriers = false,
    },
})

hl.config({
    input = {
        -- Hyphenated leaf keys inside an ordinary section.
        touchpad = {
            tap_to_click = true,
            tap_and_drag = false,
        },
        tablettool = {
            eraser_button_mode = 1,
            eraser_button_override = 0,
            pressure_range_min = 0.1,
            pressure_range_max = 0.9,
        },
    },
})

hl.config({
    decoration = {
        motion_blur = {
            enabled = true,
            samples = 9,
        },
        -- Promoted from Color to Gradient in 0.56; a bare color string still parses.
        shadow = {
            color = "rgba(1a1a1aee)",
        },
    },
})

hl.config({
    misc = {
        session_lock_blur = true,
        initial_workspace_token_timeout = 20,
    },
})

hl.config({
    master = {
        focus_master_on_close = true,
    },
})

hl.config({
    group = {
        groupbar = {
            disable_when_only = true,
        },
    },
})

-- Flattened form of a hyphenated route.
hl.config({
    input_capture = {
        enforce_barriers = true,
    },
})

